todoapi/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('completedtodo/', views.ListCompleted.as_view()),
    path('api-auth/', include('rest_framework.urls')),
    path('todos/', views.TodoListCreate.as_view()),
    path('todos/<int:pk>', views.TodoRetrieveUpdateDestroy.as_view()),
    path('todos/<int:pk>/complete', views.TodoComplete.as_view()), 
    path('signup/', views.signup),
    path('login/', views.login),
]

todowoo/urls.py
from django.contrib import admin
from django.urls import path,include
from todo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', views.signupuser, name = "signupuser"),
    path('logout/', views.logoutuser, name ="logoutuser"),
    path('current/', views.currenttodo, name="currenttodo"),
    path('completed/', views.completedtodo, name="completedtodo"),
    path('login/', views.loginuser,  name = "loginuser"),
    path('', views.home, name= "home"),
    path('create/', views.createtodo, name = "createtodo"),
    path('todo/<int:todo_pk>',views.todoview, name = 'todoview'),
    path('todo/<int:todo_pk>/complete/', views.completetodo, name = "completetodo"),
    path('todo/<int:todo_pk>/delete/', views.deletetodo, name = "deletetodo"),

    #todo api
    path('api/', include('todoapi.urls'))
    
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Todoapp(models.Model):
    name = models.CharField(max_length=100)
    memo = models.TextField(max_length= 200, blank = True)
    created_date = models.DateTimeField(auto_now_add=True)
    date_completed = models.DateTimeField(null = True, blank = True)
    important = models.BooleanField(default= False)
    user = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return self.name

todo/forms.py
from django.forms import ModelForm
from .models import Todoapp

class TodoForm(ModelForm):
    class Meta:
        model = Todoapp
        fields = ['name','memo','important']
    

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login,logout,authenticate
from .forms import TodoForm
from .models import Todoapp
from django.utils import timezone
from django.contrib.auth.decorators import login_required
# Create your views here.

def home(request):
    return render(request, 'todo/home.html')

def signupuser(request):
    if request.method == 'GET':
        return render(request, 'todo/signup.html', {'form':UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(username = request.POST['username'], password = request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('currenttodo')
            except IntegrityError:
                return render(request, 'todo/signup.html', {'form':UserCreationForm(), 'error':"The username is already taken please choose another username"})

        else:
            return render(request, 'todo/signup.html', {'form':UserCreationForm(), 'error':"The password didnt match"})


def logoutuser(request):
    if request.method == "POST":
        logout(request)
        return redirect('home')

def loginuser(request):
    if request.method == 'GET':
        return render(request, 'todo/loginuser.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(request, username = request.POST['username'], password = request.POST['password'])
        if user is None:
            return render(request, 'todo/loginuser.html', {'form':AuthenticationForm(), 'error':"The username and password didn't match"})
        else:
            login(request, user)
            return redirect('currenttodo')


@login_required
def createtodo(request):
    if request.method == "GET":
        return render(request, 'todo/createtodo.html',{'form':TodoForm()})
    else:
        try:
            form = TodoForm(request.POST)
            newtodo = form.save(commit=False)
            newtodo.user = request.user
            newtodo.save()
            return redirect('currenttodo')
        except ValueError:
           return render(request, 'todo/createtodo.html',{'form':TodoForm(), 'error': 'Bad value is passed. please try again'}) 

@login_required
def currenttodo(request):
    todos = Todoapp.objects.filter(user= request.user, date_completed__isnull = True)
    return render(request,'todo/currenttodo.html', {'todos':todos})

@login_required
def todoview(request, todo_pk):
    context = get_object_or_404(Todoapp, pk = todo_pk, user = request.user)
    if request.method == 'GET':
        form = TodoForm(instance=context)
        return render(request,'todo/todoview.html',{'context':context, 'form':form})
    else:
        try:
            form = TodoForm(request.POST, instance = context)
            form.save()
            return redirect('currenttodo')
        except ValueError:
            return render(request,'todo/todoview.html',{'context':context,'form':form, 'error':"The value you have entered is incorrect"})

@login_required
def completetodo(request, todo_pk):
    context = get_object_or_404(Todoapp, pk = todo_pk, user = request.user)
    if request.method == "POST":
        context.date_completed = timezone.now()
        context.save()
        return redirect('currenttodo')

@login_required
def deletetodo(request, todo_pk):
    context = get_object_or_404(Todoapp, pk = todo_pk, user = request.user)
    if request.method == 'POST':
        context.delete()
        return redirect('currenttodo')

@login_required
def completedtodo(request):
    context = Todoapp.objects.filter( user = request.user, date_completed__isnull = False).order_by('-date_completed')
    return render(request, 'todo/completedtodo.html',{'context':context})

todo/templates/todo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="eng">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width = device-width, initial-scale = 1" />
        <title>Todowoo</title>
        <link rel="stylesheet" href="{% static 'todo/base.css' %}" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:ital,wght@1,600&display=swap"
            rel="stylesheet">
        <!-- CSS only -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css"
            integrity="sha384-DhY6onE6f3zzKbjUPRc2hOzGAdEf4/Dz+WJwBvEYL/lkkIsI3ihufq9hk9K4lVoK" crossorigin="anonymous">
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-expand-sm navbar-dark bg-dark p-3 mb-4">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">TODO</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarcollapsed"
                    aria-controls="navbarcollapsed" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarcollapsed">
                    {% if user.is_authenticated %}
                    <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
                        <li class="nav-item todo-items">
                            <a href="{% url 'createtodo' %}" class="nav-link active">Create</a>
                        </li>
                        <li class="nav-item todo-items">
                            <a href="{% url 'completedtodo' %}" class="nav-link">Completed</a>
                        </li>
                        <li class="nav-item todo-items">
                            <a href="{% url 'currenttodo' %}" class="nav-link">Current Todo</a>
                        </li>
                        <li class="nav-item logout ">
                            <form action="{% url 'logoutuser' %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="nav-link btn btn-warning p-2">Logout</button>
                            </form>
                        </li>
                    </ul>
                        {% else %}
                    <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
                        <li class="nav-item" style="font-size: 18px; font-family: 'IBM Plex Serif', serif;">
                            <a href="{% url 'signupuser' %}" class="nav-link active">signup</a>
                        </li>
                        <li class="nav-item" style="font-size: 18px; font-family: 'IBM Plex Serif', serif;">
                            <a href="{% url 'loginuser' %}" class="nav-link">Login</a>
                        </li>
                    </ul>
                    {% endif %}
                </div>
            </div>
        </nav>
        {% block content%}
        {% endblock %}
        <!-- JavaScript Bundle with Popper.js -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/js/bootstrap.bundle.min.js"
            integrity="sha384-BOsAfwzjNJHrJ8cZidOg56tcQWfp6y72vEJ8xQ9w6Quywb24iOsW913URv1IS4GD"
            crossorigin="anonymous"></script>
    </body>

</html>

todo/templates/todo/completedtodo.html
{% extends 'todo/base.html' %}
{% block content %}
<div class="m-2 p-3">
    <h1 class="text-center"> Completed Todos </h1>
</div>
<ul class = "list group">
{% for todo in context %}
<div class = "container">
<li class = " mb-1 text-center list-group-item" style="display: block; background-color:#e0777d;"><a style = "text-decoration: none; color: black; font-size: 20px;" href="{% url 'todoview' todo.id %}">
    {% if todo.important %}<b>{% endif %}{{todo.name}}
        {% if todo.important %}</b>{% endif %}{% if todo.memo %}--{{todo.memo}}{% endif %}&ensp;&ensp;&ensp;
        {{todo.date_completed|date:'M j Y H:i'}}
</a></li>
</div>
{% endfor %}
</ul>
{% endblock %}

todo/templates/todo/createtodo.html
{% extends 'todo/base.html' %}
{% block content %}
<div class="m-2 p-3">
    <h2 class="d-flex justify-content-center"> Create New Todo </h2>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        {% if error %}
        <div class="alert alert-danger">
            {{error}}
        </div>
        {% endif %}
        <form method="POST">
            {%csrf_token%}
            <div class="form-group m-2">
                <label class="form-label" for="id_name">Name: </label>
                <input class="form-control" type="text" name="name" maxlength='100' required id="id_name" />
            </div>
            <div class="from-group m-2">
                <label class="form-label" for="id_memo">Memo: </label>
                <textarea class="form-control" name="memo" cols="40" rows="10" maxlength="200" id="id_memo"></textarea>
            </div>
            <div class="form-group m-2">
                <label class="from-label" for="id_important">Important: </label>
                <input class="form-check-input" type="checkbox" name="important" id="id_important" />
            </div>

            <div class="form-group m-2">
                <button class="btn btn-success p-2 mt-3">create</button>
            </div>
        </form>

    </div>
</div>
{% endblock %}

todo/templates/todo/currenttodo.html
{% extends 'todo/base.html'%}
{% block content%}
    <div class="m-2 p-3">
        <h1 class="text-center"> Current Todos </h1>
    </div>
    <ul class = "list-group">
        {% for todo in todos %}
        <div class = "container" >
        <li class = " mb-1 text-center list-group-item" style="display: block; background-color:darkturquoise;"><a style = "text-decoration: none; color: black; font-size: 20px;" href="{% url 'todoview' todo.id %}">
                {% if todo.important %}<b>{% endif %}{{todo.name}}
                    {% if todo.important %}</b>{% endif %}{% if todo.memo %} -- {{todo.memo|truncatechars:'30'}}{% endif %}
            </a></li>
        </div>
        {% endfor %}
    </ul>
{% endblock %}

todo/templates/todo/home.html
{% extends 'todo/base.html' %}
{% block content %}
<div class = "mt-5 p-2">
    <h3 class = 'd-flex justify-content-center'>Todo app</h3>
    <h5 class = "d-flex justify-content-center">Lets start by creating new todos that can be used in your daily life.</h5>
    <a class = "btn btn-warning col-2 m-4" style="margin-left: 35rem !important;" href = "{% url 'createtodo' %}">Let's Start</a>
</div>
{% endblock %}

todo/templates/todo/loginuser.html
{% extends 'todo/base.html' %}
{% block content %}
<div class="m-2 p-3">
    <h2 class="d-flex justify-content-center">Log In</h2>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-4">
        {% if error %}
        <div class="alert alert-danger">
            {{error}}
        </div>
        {% endif %}
        <form method="POST">
            {%csrf_token%}
            <div class="form-group m-2">
                <label class="form-label" for="id_username">Username: </label>
                <input class="form-control" type="text" autofocus autocapitalize="none" maxlength="150" name="username"
                    required id="id_username">
            </div>
            <div class="form-group m-2">
                <label class="form-label" for="id_password">Password: </label>
                <input class="form-control" type="password" autocomplete="current-password" name="password" required
                    id="id_password">
            </div>
            <button class="btn btn-success" style="margin-left: 11.1rem; margin-top: 1.45rem;">Login</button>
        </form>
    </div>
</div>
{% endblock %}

todo/templates/todo/signup.html
{% extends 'todo/base.html' %}
{% block content %}
<div class="m-2 p-1">
    <div class=" d-flex justify-content-center mb-4">
        <h2>Sign Up</h2>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-md-4">
        {% if error %}
        <div class="alert alert-danger">
            {{error}}
        </div>
        {% endif %}
        <form method="POST">
            {%csrf_token%}
            <div class="form-group m-2">
                <label class="form-label" for="id_username">Username: </label>
                <input class="form-control" type="text" name="username" required id="id_username" autocapitalize="none"
                    autocomplete="username" autofocus>
            </div>
            <div class="form-group m-2">
                <label class="form-label" for="id_password1">Password: </label>
                <input class="form-control" type="password" name="password1" required id="id_password1"
                    autocomplete="new-password" />
            </div>
            <div class="form-group m-2">
                <label class="form-label" for="id_password2">Password Confirmation: </label>
                <input class="form-control" type="password" name="password2" required id="id_password2"
                    autocomplete="new-password" />
            </div>
            <button class="btn btn-warning" style="margin-left: 11.1rem; margin-top: 1.45rem;">Signup</button>
        </form>
    </div>
</div>
{% endblock %}

todo/templates/todo/todoview.html
{% extends 'todo/base.html' %}
{% block content %}
<div class="m-2 p-3">
    <h2 class="d-flex justify-content-center"> {{context.name}} </h2>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-6">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group mb-2">
                <label class="form-label" for="id_name">Name: </label>
                <input class="form-control" type="text" value="{{context.name}}" name="name" maxlength="100" required
                    id="id_name" />
            </div>
            <div class="form-group mb-2">
                <label class="form-label" for="id_memo">Memo: </label>
                <textarea class="form-control" name="memo" rows="10" cols="40" maxlength="200"
                    id="id_memo">{{context.memo}}</textarea>
            </div>
            <div class="form-group mb-2">
                <label class="form-label" for="id_important">Important: </label>
                {% if context.important %}
                <input class="form-check-input" type="checkbox" id="id_important" name="important" checked>
                {% else %}
                <input class="form-check-input" type="checkbox" id="id_important" name="important" aria-checked="false">
                {% endif %}
            </div>
            <button class="btn btn-success mb-2 ml-5 d-inline" type="submit">Save</button>
        </form>
        <div class = "d-flex justify-content-center">
        <div class="col-md-2 mr-5" style="margin-top: -2.89rem;">
            <form method="POST" action="{% url 'completetodo' context.id %}">
                {% csrf_token %}
                <button class="btn btn-primary mb-2 mr-2 " type="submit">Complete</button>
            </form>
        </div>
        <div class = "col-md-2 mr-5" style="margin-top: -2.89rem;">
            <form method="POST" action="{% url 'deletetodo' context.id %}">
                {% csrf_token %}
                <button class="btn btn-danger mb-2 mr-2" type="submit">Delete</button>
            </form>
        </div>
    </div>
    </div>
</div>

{% endblock %}